<script setup lang="ts">
    import Navigation from "./components/Navigation.vue";
    import FooterNav from "./components/FooterNav.vue";
    const yearToday: number = new Date().getFullYear();
</script>
<template>
 <div id="terms-conditions" class="h-full w-full container mx-auto font-inter p-2">
    <Navigation />
    <article class="">
        <header class="py-2 text-[17px] text-black tracking-[-0.41px] leading-[22px] font-sf-pro-display font-medium md:text-[28px] md:font-normal md:leading-[33.41px] md:tracking-[0.36px]">Terms and Conditions</header>
        <section class="py-2">
            <h2>Terms and Conditions for Smart Coupon Finder Chrome Extension</h2>
            <p>Last Updated: {{ yearToday }}</p>

            <h3>1. Introduction</h3>

            <p>Welcome to the Smart Coupon Finder Chrome Extension ("Extension"). By using this Extension, you agree to comply with and be bound by the following Terms and Conditions ("Terms"). If you do not agree to these Terms, you should not use the Extension.</p>

            <h3>2. Acceptance of Terms</h3>

            <p>By installing, accessing, or using the Smart Coupon Finder Extension, you accept and agree to be bound by these Terms. These Terms apply to all users of the Extension.</p>

            <h3>3. Description of Service</h3>

            <p>The Smart Coupon Finder Extension allows users to:</p>
            <p>- Automatically detect and apply coupon codes at checkout on supported websites.</p>
            <p>- Fetch and display a list of available coupons for specific websites.</p>
            <p>- Use AI-generated coupons where applicable.</p>
            <p>- Integrate affiliate links when browsing or purchasing on partner websites.</p>

            <p>The Extension is provided for informational and convenience purposes only. We do not guarantee that all coupons will be valid or that discounts will always be applied successfully.</p>

            <h3>4. License and Restrictions</h3>

            <h4>4.1 License</h4>
            <p>Subject to these Terms, we grant you a personal, non-exclusive, non-transferable, revocable license to use the Extension for personal use.</p>

            <h4>4.2 Restrictions</h4>
            <p>You agree not to:</p>
            <p>- Modify, copy, distribute, or create derivative works of the Extension.</p>
            <p>- Reverse-engineer, decompile, or disassemble the Extension.</p>
            <p>- Use the Extension for any illegal or unauthorized purpose.</p>
            <p>- Remove or alter any proprietary notices or labels.</p>

            <h3>5. Affiliate Links</h3>

            <p>The Extension may modify website URLs to include affiliate links, which generate commissions for the developer when you make purchases through supported retailers. By using this Extension, you consent to the inclusion of such links.</p>

            <h4>5.1 Disclaimer on Affiliate Links</h4>
            <p>Affiliate links do not affect your purchase or the price you pay. We are not responsible for any issues arising from purchases made through these affiliate links, including order disputes or return policies.</p>

            <h3>6. Use of Coupons</h3>

            <p>The Extension automatically detects coupon fields and applies available coupons based on information retrieved from third-party services or generated by AI. However, we make no guarantees that:</p>
            <p>- Coupons will always be available or valid.</p>
            <p>- The best discount will always be applied.</p>
            <p>- All supported websites will accept the applied coupon.</p>

            <p>You are solely responsible for ensuring that any coupon applied through the Extension is valid, and we are not liable for any loss or damages arising from invalid coupons.</p>

            <h3>7. Third-Party Services</h3>

            <p>The Extension may integrate third-party services (such as CouponGPT or CouponAPI) to provide coupon codes and other related features. We are not responsible for the availability, accuracy, or content provided by these services. Your interaction with any third-party services is governed by their respective terms and conditions.</p>

            <h3>8. Privacy Policy</h3>

            <p>By using the Extension, you agree to our [Privacy Policy](#), which explains how we collect, use, and protect your personal information.</p>

            <h3>9. Disclaimer of Warranties</h3>

            <p>The Extension is provided "as is" and "as available" without any warranty of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p> 

            <p>We do not guarantee that:</p>
            <p>- The Extension will meet your requirements.</p>
            <p>- The Extension will function without errors or interruptions.</p>
            <p>- Coupons will always apply correctly or result in savings.</p>

            <h3>10. Limitation of Liability</h3>

            <p>To the fullest extent permitted by law, in no event shall we be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with your use of the Extension, including but not limited to loss of data, savings, profits, or any other tangible or intangible losses.</p>

            <h3>11. Indemnification</h3>

            <p>You agree to indemnify, defend, and hold us harmless from any claims, damages, liabilities, costs, or expenses (including reasonable legal fees) arising out of or in connection with your use of the Extension, your violation of these Terms, or your infringement of any third-party rights.</p>

            <h3>12. Modification of Terms</h3>

            <p>We reserve the right to modify these Terms at any time. Any changes will be effective immediately upon posting the updated Terms. It is your responsibility to review the Terms periodically. Your continued use of the Extension after changes to the Terms will signify your acceptance of those changes.</p>

            <h3>13. Termination</h3>

            <p>We reserve the right to terminate or suspend your access to the Extension at any time, without prior notice or liability, if you breach these Terms or for any other reason.</p>

            <h3>14. Governing Law</h3>

            <p>These Terms are governed by and construed in accordance with the laws of [Insert Jurisdiction]. Any disputes arising from or relating to these Terms will be resolved in the courts of [Insert Jurisdiction].</p>

            <h3>15. Contact Information</h3>

            <p>If you have any questions about these Terms or the Extension, please contact us at:</p>
            <p>- <strong>Email:</strong> [info@smartcouponfinder.co]</p>
            <p>- <strong>Phone:</strong> [+639055192238]</p>
            </section>
        <FooterNav />
    </article>
 </div>
</template>
